Day_8/Models/Employe.cs
using System;
using System.Collections.Generic;

namespace Day_8.Models;

public partial class Employe
{
    public int Id { get; set; }

    public string Password { get; set; } = null!;

    public DateTime? BirthDay { get; set; }

    public string? Adress { get; set; }

    public string? Email { get; set; }

    public int? Age { get; set; }

    public bool Gender { get; set; }

    public int GroupId { get; set; }

    public bool Status { get; set; }

    public int? IsSystem { get; set; }

    public string? UserName { get; set; }

    public virtual Group? Group { get; set; }
    public virtual ICollection<EmployeRole> EmployeRoles { get; set; }
}

Day_8/Controllers/EmployeController.cs
using Day_8.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Day_8.Controllers
{
    public class EmployeController : Controller
    {
        private EmployessContext _db = new EmployessContext();

        public IActionResult Index()
        {
            return View();
        }

        //public IActionResult List()
        //{
        //    return View(_db.Employes.ToList());
        //}

        //public ActionResult ShowDetail()
        //{
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Add(Employe employe)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var check = _db.Employes.FirstOrDefault(s => s.Id == employe.Id);
        //        if (check == null)
        //        {
        //            _db.Employes.Add(employe);
        //            _db.SaveChanges();
        //            return RedirectToAction("List");
        //        }
        //        else
        //        {
        //            ViewBag.error = "ID exits";
        //            return View();
        //        }


        //    }
        //    return View();
        //}
        [HttpGet]
        public async Task<IActionResult> ShowDetail()
        {
            var userEmail = HttpContext.Session.GetString("auth");
            if ( string.IsNullOrEmpty(userEmail) || _db.Employes == null)
            {
                return NotFound();
            }

            var em = await _db.Employes
                .FirstOrDefaultAsync(m => m.Email == userEmail);
            if (em == null)
            {
                return NotFound();
            }


            return View(em);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _db.Employes == null)
            {
                return NotFound();
            }

            var em = await _db.Employes.FindAsync(id)
;
            if (em == null)
            {
                return NotFound();
            }
            return View(em);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Employe employe)
        {
            if (id != employe.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(employe);
                    await _db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployesExists(employe.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employe);
        }
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _db.Employes == null)
            {
                return NotFound();
            }

            var em = await _db.Employes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (em == null)
            {
                return NotFound();
            }

            return View(em);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_db.Employes == null)
            {
                return Problem("Entity set 'DataUserContext.Usertbls'  is null.");
            }
            var user = await _db.Employes.FindAsync(id)
;
            if (user != null)
            {
                _db.Employes.Remove(user);
            }

            await _db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool EmployesExists(int id)
        {
            return _db.Employes.Any(e => e.Id == id);
        }

        

        public ActionResult Logout()
        {
            HttpContext.Session.Remove("Id");
            return RedirectToAction("Login", "Account");
        }
    }
}

Day_8/Views/Employe/Delete.cshtml
 @model Day_8.Models.Employe

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="List">Back to List</a>
    </form>
</div>

Day_8/Views/Employe/Edit.cshtml
@model Day_8.Models.Employe

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employe</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BirthDay" class="control-label"></label>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
               <select id="gender" name="Gender">
                      <option value="true">Nam</option>
                      <option value="false">Nu</option>
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Day_8/Views/Employe/Index.cshtml
@model Day_8.Models.Employe
<div>
    <h1>WelCome To Employes</h1> 
</div>
    <div class="text-center" >
         <a asp-controller="Employe" asp-action="ShowDetail">Details</a>
    </div>

Day_8/Views/Employe/ShowDetail.cshtml
@model Day_8.Models.Employe

@{
    ViewData["Title"] = "ShowDetail";
}

<h1>ShowDetail</h1>

<div>
    <h4>Employe</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BirthDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model?.Id">Delete</a>
</div>